#! /usr/bin/env python3
'''
辞典
'''
# pylint: disable=I0011,C0103,R0913

import hashlib
from urllib.parse import urlencode
from random import random
from sys import argv
import requests

APPKEY = '' #应用ID
KEY = '' # 应用密钥
APIURL = 'https://openapi.youdao.com/api?'

def queryUrl(q, fr, to, appKey, salt, sign):
    '''
        返回api调用URL
    '''

    data = {
        'q':q,
        'from':fr,
        'to':to,
        'appKey':appKey,
        'salt':salt
    }
    return APIURL + urlencode(data) +'&sign='+sign


def showExplains(w):
    '''
        输出词条
    '''

    print('======')
    print('所查：'+w['query'])
    print('======')
    #基本释意
    if 'basic' in w:
        print('基本释意：')
        print('\t---')
        print('\t音标：', w['basic']['phonetic'])
        print('\t---')
        explains = w['basic']['explains']
        print('\t释意：')
        for e in explains:
            print('\t'+e)
        print('======')
    if 'web' in w:
        print('网络释意：')
        for webe in w['web']:
            print('\t'+webe['key'], end=': ')
            for v in webe['value']:
                print(v, end=', ')
            print()
        print('======')
    print('机器翻译：')
    for me in w['translation']:
        print('\t'+me)
    print('======')

queryString = argv[1]
randomSalt = str(random())
MD5 = hashlib.md5()
MD5.update((APPKEY+queryString+randomSalt+KEY).encode())
md5Sign = MD5.hexdigest()
url = queryUrl(q=queryString, fr='auto', to='auto', appKey=APPKEY, salt=randomSalt, sign=md5Sign)
jsondata = None
response = requests.get(url)
if response.status_code == 200:
    jsondata = response.json()
showExplains(jsondata)
